package com.OBS.enums;

public enum SearchOperation {
    GREATER_THAN,
    LESS_THAN,
    GREATER_THAN_EQUAL,
    LESS_THAN_EQUAL,
    NOT_EQUAL,
    EQUAL,
    MATCH,
    MATCH_START,
    MATCH_END,
    IN,
    NOT_IN,
    EQUAL_NULL,
    NOT_EQUAL_NULL,
    GREATER_THAN_EQUAL_DATE,
    GREATER_THAN_DATE,
    LESS_THAN_EQUAL_DATE,
    LESS_THAN_DATE,
    EQUAL_DATE,
    NOT_EQUAL_DATE,
}
